services:
  ticketing-api:
    env_file:
      - .env.dev
    container_name: ticketing-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_DATA_REDIS_HOST: redis
  redis:
    env_file:
      - .env.dev
    image: 'redis:latest'
    container_name: ticketing-redis-dev
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --appendonly
      - yes
      - --requirepass
      - "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    # prometheus
    # grafana
volumes: # 볼륨 선언
  redis_data:
