services:
  ticketing-api:
    env_file:
      - .env.prod
    container_name: ticketing-api-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_REDIS_HOST: redis
  mysql:
    env_file:
      - .env.prod
    image: 'mysql:latest'
    container_name: ticketing-mysql-prod
    environment:
      TZ: Asia/Seoul # 시간대 설정 추가 (DB 데이터 시간 정합성을 위해 필수)
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    env_file:
      - .env.prod
    image: 'redis:latest'
    container_name: ticketing-redis-prod
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --appendonly
      - yes
      - --requirepass
      - "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    # prometheus
    # grafana
volumes: # 볼륨 선언
  mysql_data:
  redis_data:
